# Generated by Django 3.2 on 2022-12-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kat', models.AutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriGallery',
            fields=[
                ('id_katGal', models.AutoField(primary_key=True, serialize=False)),
                ('kategoriGal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id_gal', models.AutoField(primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=500)),
                ('gallery', models.FileField(blank=True, upload_to='gallery')),
                ('kategoriGal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApps.kategorigallery')),
            ],
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False)),
                ('penulis', models.CharField(max_length=20)),
                ('judul', models.CharField(max_length=50)),
                ('isi_artikel', models.CharField(max_length=2000)),
                ('keterangan', models.CharField(max_length=100)),
                ('gambar', models.FileField(blank=True, upload_to='gambar')),
                ('published', models.DateField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApps.kategori')),
            ],
        ),
    ]
